// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protocol/cloudstate/crdt.proto

#include "protocol/cloudstate/crdt.pb.h"
#include "protocol/cloudstate/crdt.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace cloudstate {
namespace crdt {

static const char* Crdt_method_names[] = {
  "/cloudstate.crdt.Crdt/handle",
};

std::unique_ptr< Crdt::Stub> Crdt::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Crdt::Stub> stub(new Crdt::Stub(channel));
  return stub;
}

Crdt::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_handle_(Crdt_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::cloudstate::crdt::CrdtStreamIn, ::cloudstate::crdt::CrdtStreamOut>* Crdt::Stub::handleRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::cloudstate::crdt::CrdtStreamIn, ::cloudstate::crdt::CrdtStreamOut>::Create(channel_.get(), rpcmethod_handle_, context);
}

void Crdt::Stub::experimental_async::handle(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::cloudstate::crdt::CrdtStreamIn,::cloudstate::crdt::CrdtStreamOut>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::cloudstate::crdt::CrdtStreamIn,::cloudstate::crdt::CrdtStreamOut>::Create(stub_->channel_.get(), stub_->rpcmethod_handle_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::cloudstate::crdt::CrdtStreamIn, ::cloudstate::crdt::CrdtStreamOut>* Crdt::Stub::AsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::cloudstate::crdt::CrdtStreamIn, ::cloudstate::crdt::CrdtStreamOut>::Create(channel_.get(), cq, rpcmethod_handle_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::cloudstate::crdt::CrdtStreamIn, ::cloudstate::crdt::CrdtStreamOut>* Crdt::Stub::PrepareAsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::cloudstate::crdt::CrdtStreamIn, ::cloudstate::crdt::CrdtStreamOut>::Create(channel_.get(), cq, rpcmethod_handle_, context, false, nullptr);
}

Crdt::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Crdt_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Crdt::Service, ::cloudstate::crdt::CrdtStreamIn, ::cloudstate::crdt::CrdtStreamOut>(
          std::mem_fn(&Crdt::Service::handle), this)));
}

Crdt::Service::~Service() {
}

::grpc::Status Crdt::Service::handle(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::cloudstate::crdt::CrdtStreamOut, ::cloudstate::crdt::CrdtStreamIn>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace cloudstate
}  // namespace crdt

