// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protocol/cloudstate/event_sourced.proto

#include "protocol/cloudstate/event_sourced.pb.h"
#include "protocol/cloudstate/event_sourced.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace cloudstate {
namespace eventsourced {

static const char* EventSourced_method_names[] = {
  "/cloudstate.eventsourced.EventSourced/handle",
};

std::unique_ptr< EventSourced::Stub> EventSourced::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EventSourced::Stub> stub(new EventSourced::Stub(channel));
  return stub;
}

EventSourced::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_handle_(EventSourced_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* EventSourced::Stub::handleRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>::Create(channel_.get(), rpcmethod_handle_, context);
}

void EventSourced::Stub::experimental_async::handle(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::cloudstate::eventsourced::EventSourcedStreamIn,::cloudstate::eventsourced::EventSourcedStreamOut>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::cloudstate::eventsourced::EventSourcedStreamIn,::cloudstate::eventsourced::EventSourcedStreamOut>::Create(stub_->channel_.get(), stub_->rpcmethod_handle_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* EventSourced::Stub::AsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>::Create(channel_.get(), cq, rpcmethod_handle_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* EventSourced::Stub::PrepareAsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>::Create(channel_.get(), cq, rpcmethod_handle_, context, false, nullptr);
}

EventSourced::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EventSourced_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< EventSourced::Service, ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>(
          std::mem_fn(&EventSourced::Service::handle), this)));
}

EventSourced::Service::~Service() {
}

::grpc::Status EventSourced::Service::handle(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace cloudstate
}  // namespace eventsourced

