// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protocol/cloudstate/event_sourced.proto
// Original file comments:
// Copyright 2019 Lightbend Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// gRPC interface for Event Sourced Entity user functions.
//
#ifndef GRPC_protocol_2fcloudstate_2fevent_5fsourced_2eproto__INCLUDED
#define GRPC_protocol_2fcloudstate_2fevent_5fsourced_2eproto__INCLUDED

#include "protocol/cloudstate/event_sourced.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace cloudstate {
namespace eventsourced {

// The Entity service
class EventSourced final {
 public:
  static constexpr char const* service_full_name() {
    return "cloudstate.eventsourced.EventSourced";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // The stream. One stream will be established per active entity.
    // Once established, the first message sent will be Init, which contains the entity ID, and,
    // if the entity has previously persisted a snapshot, it will contain that snapshot. It will
    // then send zero to many event messages, one for each event previously persisted. The entity
    // is expected to apply these to its state in a deterministic fashion. Once all the events
    // are sent, one to many commands are sent, with new commands being sent as new requests for
    // the entity come in. The entity is expected to reply to each command with exactly one reply
    // message. The entity should reply in order, and any events that the entity requests to be
    // persisted the entity should handle itself, applying them to its own state, as if they had
    // arrived as events when the event stream was being replayed on load.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>> handle(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>>(handleRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>> Asynchandle(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>>(AsynchandleRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>> PrepareAsynchandle(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>>(PrepareAsynchandleRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // The stream. One stream will be established per active entity.
      // Once established, the first message sent will be Init, which contains the entity ID, and,
      // if the entity has previously persisted a snapshot, it will contain that snapshot. It will
      // then send zero to many event messages, one for each event previously persisted. The entity
      // is expected to apply these to its state in a deterministic fashion. Once all the events
      // are sent, one to many commands are sent, with new commands being sent as new requests for
      // the entity come in. The entity is expected to reply to each command with exactly one reply
      // message. The entity should reply in order, and any events that the entity requests to be
      // persisted the entity should handle itself, applying them to its own state, as if they had
      // arrived as events when the event stream was being replayed on load.
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void handle(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::cloudstate::eventsourced::EventSourcedStreamIn,::cloudstate::eventsourced::EventSourcedStreamOut>* reactor) = 0;
      #else
      virtual void handle(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::cloudstate::eventsourced::EventSourcedStreamIn,::cloudstate::eventsourced::EventSourcedStreamOut>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* handleRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* AsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* PrepareAsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>> handle(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>>(handleRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>> Asynchandle(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>>(AsynchandleRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>> PrepareAsynchandle(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>>(PrepareAsynchandleRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void handle(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::cloudstate::eventsourced::EventSourcedStreamIn,::cloudstate::eventsourced::EventSourcedStreamOut>* reactor) override;
      #else
      void handle(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::cloudstate::eventsourced::EventSourcedStreamIn,::cloudstate::eventsourced::EventSourcedStreamOut>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* handleRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* AsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* PrepareAsynchandleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_handle_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // The stream. One stream will be established per active entity.
    // Once established, the first message sent will be Init, which contains the entity ID, and,
    // if the entity has previously persisted a snapshot, it will contain that snapshot. It will
    // then send zero to many event messages, one for each event previously persisted. The entity
    // is expected to apply these to its state in a deterministic fashion. Once all the events
    // are sent, one to many commands are sent, with new commands being sent as new requests for
    // the entity come in. The entity is expected to reply to each command with exactly one reply
    // message. The entity should reply in order, and any events that the entity requests to be
    // persisted the entity should handle itself, applying them to its own state, as if they had
    // arrived as events when the event stream was being replayed on load.
    virtual ::grpc::Status handle(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_handle() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status handle(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthandle(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_handle<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_handle() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->handle(context); }));
    }
    ~ExperimentalWithCallbackMethod_handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status handle(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* handle(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::cloudstate::eventsourced::EventSourcedStreamIn, ::cloudstate::eventsourced::EventSourcedStreamOut>* handle(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_handle<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_handle<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_handle() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status handle(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_handle() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status handle(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthandle(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_handle : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_handle() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->handle(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_handle() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status handle(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cloudstate::eventsourced::EventSourcedStreamOut, ::cloudstate::eventsourced::EventSourcedStreamIn>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* handle(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* handle(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace eventsourced
}  // namespace cloudstate


#endif  // GRPC_protocol_2fcloudstate_2fevent_5fsourced_2eproto__INCLUDED
